### ISSUE TITLE
[Tracking] To-Do-List

### ISSUE THREAD

**Issue by DennisFGardner** [DennisFGardner/radial-integral#1]
## To-Do-List

- [ ] Learn how to do a fast radial integral in 2D
- [ ] Adapt the code so I can exclude NaN
- [ ] Modify the code so the center of the integral can be specified

**Comment by DennisFGardner** [comment]
I figured how the code works that I found on the MATLAB file exchange: https://www.mathworks.com/matlabcentral/fileexchange/18102-radial-scan 

A X, Y grid is generated and converted to polor coordinates using cart2pol. The R output of cart2pol is sorted using sort. The image is then "sorted" in the same way using the index output from sort. Finally the code reshapes the linear array into cols. The number of cols in an input from the user.

**Comment by DennisFGardner** [comment]
Corinne suggested I use nanmean to get around the NaN problem.

**Comment by DennisFGardner** [comment]
I implemented nanmean. It's preforming as expected. No trouble with NaNs.
